import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import profilePicture from '../../public/images/profile/qa-pic-2.png';
import flagBR from '../../public/images/brazil.png';
import flagEN from '../../public/images/us.png';
import AnimatedText from '@/components/AnimatedText';
import { LinkArrow } from '@/components/Icons';

export default function Home() {
  return (
    <>
      <Head>
        <title>Lourena Ohara</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Lourena  Ohara" className='!text-5xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />
              <div className='my-4 text-base font-medium'>
                <p className='text-2xl text-emerald-900 font-bold dark:text-primaryDark lg:w-full'>Analista de Testes e Qualidade de Software (QA) <br /><br /></p>
                Vasto conhecimento em testes, automatizados e manuais. Levantamento de requisitos, casos de uso, caso de testes, usabilidade, documentações de produtos e processos. Suporte a diferentes níveis de usuário. Desenvolvimento mobile, programação em Python, Java, JavaScript e experiência com desenvolvimento também nessas linguagens.
              </div>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href='/pt.pdf' target={"_blank"}
                  className='flex items-center mr-4 bg-dark text-light p-1.5 px-4 
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light'
                >CV <Image src={flagBR} alt='br' className={'w-3.5 ml-2'} />
                  <LinkArrow className={'w-3.5 ml-2'} />
                </Link>
                <Link href='/en.pdf' target={"_blank"}
                  className='flex items-center bg-dark text-light p-1.5 px-4
                  rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                  border border-solid border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                  hover:dark:border-light'
                >CV <Image src={flagEN} alt='en' className={'w-3.5 ml-2'} />
                  <LinkArrow className={'w-3.5 ml-2'} />
                </Link>
                <Link href='malito:lourena6ohara@gmail.com' target={"_blank"}
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light'
                >Contato</Link>
              </div>
            </div>
            <div className='w-2/3 ml-28 md:w-2/3'>
              <Image src={profilePicture} alt='Profile' className='w-full h-auto rounded-2xl lg:hidden
              md:inline-block md:w-full'
              priority
              sizes='(max-widht: 768px) 100vw,
              (max-widht: 1200px) 66vw,
              66vw'
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
